plugins {
    id 'com.android.application'
}

android {

    namespace 'com.la87hn.la87laprimera'
    compileSdk 36

    defaultConfig {
        applicationId "com.la87hn.la87laprimera"
        minSdkVersion 21
        targetSdk 36
        versionCode 15
        versionName "5.0.3"
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint {
        disable 'OldTargetApi', 'GradleDependency'
    }

}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "androidx.cardview:cardview:1.0.0"
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.work:work-runtime-ktx:2.9.0'
    implementation "androidx.multidex:multidex:2.0.1"
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.squareup.okhttp3:okhttp:4.9.1'
    implementation 'com.google.code.gson:gson:2.8.6'

    implementation 'com.github.bumptech.glide:glide:4.12.0'
    implementation 'androidx.annotation:annotation:1.8.0'
    implementation 'com.squareup.retrofit2:retrofit:2.10.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.10.0'
    implementation 'com.squareup.okhttp3:okhttp:5.0.0-alpha.9'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.9'

    implementation "androidx.media3:media3-session:1.3.1"
    implementation "androidx.media3:media3-exoplayer:1.3.1"
    implementation "androidx.media3:media3-exoplayer-dash:1.3.1"
    implementation "androidx.media3:media3-exoplayer-hls:1.3.1"
    implementation "androidx.media3:media3-exoplayer-smoothstreaming:1.3.1"
    implementation "androidx.media3:media3-exoplayer-rtsp:1.3.1"

    implementation 'com.karumi:dexter:6.0.2'
    implementation 'com.makeramen:roundedimageview:2.3.0'
    implementation "com.github.gsotti:EqualizerView:v0.2"
    implementation 'com.github.mohammadima3oud:Android-Intent-Library:1.0.0'

}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}